name = "IntegrationTests"
uuid = "6be7cfa2-1838-408e-bc49-3a824ac3a1fb"
authors = ["Simeon Ehrig <s.ehrig@hzdr.de> and contributors"]
version = "1.0.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
